api_frontend_shop:
    resource: '../../../**/{*FrontendApiPoint.php}'
    type: attribute
    prefix: /api/example-project/shop
    host: '%api_host%'
    schemes: '%api_scheme%'

when@dev:
    api_doc.example_project_shop.redocly: &api_doc_redocly
        path: /api/example-project/shop/doc.html
        methods: GET
        defaults: { _controller: nelmio_api_doc.controller.redocly, area: example_project_shop }

    api_doc.example_project_shop.swagger: &api_doc_json
        path: /api/example-project/shop/doc.json
        methods: GET
        defaults: { _controller: nelmio_api_doc.controller.swagger, area: example_project_shop }

when@stage:
    api_doc.example_project_shop.redocly: *api_doc_redocly
    api_doc.example_project_shop.swagger: *api_doc_json
