doctrine:
    orm:
        mappings:
            AppShopBundle:
                type: attribute
                dir: '%kernel.project_dir%/src/EmployeePortal/Shop'
                is_bundle: false
                prefix: App\EmployeePortal\Shop
