when@dev: &api_doc
    nelmio_api_doc:
        areas:
            example_project_blog:
                path_patterns:
                    - ^/api/example-project/blog/(?!/doc$)
                documentation:
                    info:
                        title: EmployeePortal Blog
                        description: This is an awesome <b>Module</b>!
                        version: 1.0.0
when@stage: *api_doc
